### ISSUE TITLE
Decide what to do with the make details bar

### ISSUE THREAD

**Issue by cadecairos** [mozilla/make-valet#67]
This thing....

![The make details bar](https://cloud.githubusercontent.com/assets/438003/9995205/dd01fc16-604e-11e5-867c-a0ac78b8efbc.png)

....is currently an iframe that is served from webmaker.org. This was originally done to allow for actions that required a user session (favoring and reporting). We won't need that anymore.

We have two options:

a) re-implement it and render it from make-valet

b) remove it entirely

![](https://assets.pando.com/uploads/2013/10/red-pill-or-blue-pill.jpg)

@ashleygwilliams @jbuck @xmatthewx @simonwex

**Comment by humphd** [comment]
In the new Thimble, and with Publish, we've gone the route of injecting a `<div>` and a `<script>` and dynamically rendering a `Remix` button.  Discussions about how we're going to evolve it are happening in https://github.com/mozilla/thimble.webmaker.org/issues/1107.

We're also discussing a "copy-on-write" approach for old Thimble makes, to have the remix button take you to the new Thimble and create a single-file `index.html` project out of an old Thimble make.  I know there is interest from @simonwex in having the old links continue to work for this reason.

cc @flukeout

**Comment by jbuck** [comment]
@humphd For the old thimble makes we'll be keeping the Remix button, the question here is whether to keep the collapsible details bar by rendering it on the make-valet, or simply remove it.

**Comment by jbuck** [comment]
Unless anyone says otherwise, lets remove the iframe

**Comment by cadecairos** [comment]
@jbuck so you think we should serve the make without the details bar or anything data in it currently?

**Comment by jbuck** [comment]
Leave the details bar, but remove the click-to-expand function and the iframe

**Comment by cadecairos** [comment]
Won't that just cause crazy CSS issues, especially in thimble?

**Comment by jbuck** [comment]
But thimble makes already have a details bar?

**Comment by jbuck** [comment]
Like, https://jon.makes.org/thimble/LTM3MDU0MDU0NA==/la-premi%C3%A8re-page-de-sphinx totally has a details bar

**Comment by cadecairos** [comment]
oh yeah, I forgot there are actually three iframes there. the wrapper, the content and the make detials.

**Comment by cadecairos** [comment]
gonna call this resolved. work being done in #68
